apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-service
  labels:
    app: cart-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cart-service
  template:
    metadata:
      labels:
        app: cart-service
    spec:
      containers:
        - name: cart-service
          image: "{{ .Values.images.cart.repository }}:{{ .Values.images.tag }}"
          imagePullPolicy: Always
          ports:
            - containerPort: 4003
          env:
            - name: DB_HOST
              value: "mysql"

            - name: DB_USER
              value: "root"

            - name: DB_PASSWORD
              value: "root"

            - name: DB_NAME
              value: "cart_db"

            - name: JWT_SECRET
              value: "base64:MyAyH94zgpW/jFFmSEhkKaQ/Rr4i9L7gJBmyyPpgy8Q="

            - name: PRODUCT_SERVICE_URL
              value: "http://product-service:4002"

            - name: PORT
              value: "4003"
