apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.images.frontend.repository }}:{{ .Values.images.frontend.tag }}"
          imagePullPolicy: Always

          ports:
            - containerPort: 3000

          env:
            - name: API_BASE_URL
              value: "http://api-gateway:4000"

            - name: SECRET_KEY
              value: "change-this-secret-in-production"

            - name: PORT
              value: "3000"
